---

# Create a VPC with dedicate tenancy and a couple of tags

- name: Create new VPC with given configurations
  aws_access_key: "{{ec2_access_key}}"
  aws_secret_key: "{{ec2_secret_key}}"
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ vpc_region }}"
    tags:
      auto-gen-source: "ansible"
    tenancy: "{{ vpc_tenancy }}"
  register: ansible_vpc
